//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class LargeBread : Decorator
{
	private SandWich SandWich
	{
		get;
		set;
	}

	public override string Add()
	{
		throw new System.NotImplementedException();
	}

}

