//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Complejidad
{
	public virtual void hasDuplicateValuesLineal(int Numbers)
	{
		throw new System.NotImplementedException();
	}

	public virtual void hasDuplicateValuesExponential(int Numbers)
	{
		throw new System.NotImplementedException();
	}

	public virtual void hasDuplicateValuesCuadratic(int Numbers)
	{
		throw new System.NotImplementedException();
	}

}

