//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Adaptador : Sharing
{
	public virtual void Shared(string Message, SharerType SharedType)
	{
		throw new System.NotImplementedException();
	}

	public virtual void shareEveryWhere(string Message)
	{
		throw new System.NotImplementedException();
	}

}

