//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Messaging
{
	public virtual BridgeSecureMessenger BridgeSecureMessenger
	{
		get;
		set;
	}

	public virtual BridgeDestructingMessenger BridgeDestructingMessenger
	{
		get;
		set;
	}

	public abstract void Send(string Message);

}

