//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SelfDestructingEZMessenger : BridgeDestructingMessenger
{
	public virtual void Send(string Message)
	{
		throw new System.NotImplementedException();
	}

}

